### ISSUE TITLE
End of Life PHP 7.0 / 7.1 / 7.2

### ISSUE THREAD

**Issue by dasrecht** [uselagoon/lagoon-images#236]
As PHP 7.0 trough to PHP 7.2 will or is already out of support we should make sure documentation and images are updated

Documentation Update: 
-https://lagoon.readthedocs.io/en/v1.9.1/using_lagoon/docker_images/php-fpm/

Same process as with https://github.com/amazeeio/lagoon/issues/1214

**Comment by AlannaBurke** [comment]
The current docs are already up to date: https://docs.lagoon.sh/lagoon/docker-images/php-fpm

**Comment by tobybellwood** [comment]
closed in #281 - docco to be updated in uselagoon/lagoon
