### ISSUE TITLE
Redirect /index.php/* to /* in Drupal Nginx images

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon-images#237]
See https://www.drupal.org/forum/support/post-installation/2020-04-06/solved-drupal-8-is-adding-indexphp-in-url for background. In short, Drupal 8 has valid routes for `/index.php/blah` where the friendly URL is `/blah`. This only serves to confuse Google, and the end user.

There is best practice in https://www.nginx.com/resources/wiki/start/topics/recipes/drupal/ to fix this with

```
    # Enforce clean URLs
    # Removes index.php from urls like www.example.com/index.php/my-page --> www.example.com/my-page
    # Could be done with 301 for permanent or other redirect codes.
    if ($request_uri ~* "^(.*/)index\.php/(.*)") {
        return 307 $1$2;
    }
```

We should add this to the base images.

**Comment by tobybellwood** [comment]
Closing as no further recent conversation - please reopen if this use case or issue still exists.
