### ISSUE TITLE
Massive performance decrease when enabling XDEBUG_ENABLE

### ISSUE THREAD

**Issue by fmuellerprevion** [uselagoon/lagoon-images#238]
**Describe the bug**
When using our VMs, the loading times vary between one second on small and up to four seconds on very complex projects.

When enabling XDebug (XDEBUG_ENABLE: "true" in docker-compose.yml), the site slows down dramatically. Loading times vary between one and 10 Minutes! 

The com.docker.hyperkit process takes up most of the physical CPUs performance when loading the site.

**To Reproduce**
1. Go to docker-compose.yml
2. Set XDEBUG_ENABLE to "true"
3. docker-compose up -d
4. Load your application

**Expected behavior**
A decrease in loading time to several seconds is absolutely ok. Up to 20 Seconds would be takeable.

**Screenshots**

Docker configuration

<img width="503" alt="bildschirmfoto 2019-01-30 um 14 08 57" src="https://user-images.githubusercontent.com/26752987/51983379-cd546580-2498-11e9-87b7-70b697e83e4d.png">

**Additional context**
none

**Comment by rocketeerbkw** [comment]
Looks like there's a fix for the sleep/wake issue now https://github.com/docker/for-mac/issues/3455#issuecomment-1064614213

//cc @twerthmueller

**Comment by twerthmueller** [comment]
Thanks @rocketeerbkw, will check that. But I switched to an M1 macbook and Docker Desktop 4.5.0. Currently I do not expect this behaviour anymore.

**Comment by Feng-Shui** [comment]
As per @twerthmueller, I'm not getting this issue anymore on an M1 MBP.  Same Docker Desktop version.

**Comment by rocketeerbkw** [comment]
Both docker for mac and Xdebug have upstream fixes for the timing issue that causes performance problems in x86 macs.
