### ISSUE TITLE
Support XDebug 3

### ISSUE THREAD

**Issue by dan2k3k4** [uselagoon/lagoon-images#40]
As Xdebug 3 has just been released, there are a few points to note in the [upgrade guide](https://xdebug.org/docs/upgrade_guide).

Currently, we install [xdebug via pecl](https://github.com/uselagoon/lagoon-images/blob/492fdf5c73a5f5b12cfb9dbdd3751c1969c98faa/images/php-fpm/7.4.Dockerfile#L78) and as of today, that will install version 3.0.0.

We could replace the usage of `xdebug.remote_enable = on` with `xdebug.mode=debug`, which is currently found in the 
[00-lagoon-php.ini.tpl](https://github.com/uselagoon/lagoon-images/blob/8ff8e503d57033159a49b106bb03826ff294f3df/images/php-fpm/00-lagoon-php.ini.tpl#L17) file and the [php.ini](https://github.com/uselagoon/lagoon-images/blob/8ff8e503d57033159a49b106bb03826ff294f3df/images/php-fpm/php.ini#L1587) file for this repository.

The `XDEBUG_CONFIG` env var has been replaced with `XDEBUG_SESSION` which would require updating the [61-php-xdebug-cli-env.sh](https://github.com/uselagoon/lagoon-images/blob/main/images/php-cli/61-php-xdebug-cli-env.sh#L7) file.

`xdebug.remote_host` is replaced with `xdebug.client_host` which is found in [60-php-xdebug.sh](https://github.com/uselagoon/lagoon-images/blob/main/images/php-fpm/entrypoints/60-php-xdebug.sh#L29)

`xdebug.remote_log` is replaced with `xdebug.log` which is found in [60-php-xdebug.sh](https://github.com/uselagoon/lagoon-images/blob/main/images/php-fpm/entrypoints/60-php-xdebug.sh#L32)

There might be a few other things that need tweaking.

**Comment by dan2k3k4** [comment]
In PR #41, I am not sure if we also need to `EXPOSE 9003` as the default Xdebug port was changed from 9000 to 9003. We have a few places where we expose port 9000, but those don't seem to be exposed for Xdebug purposes.

**Comment by tobybellwood** [comment]
I think we might just pin PECL to Xdebug 2.9.8 for this upcoming release, and put this through more thorough testing before going to 3.

**Comment by dan2k3k4** [comment]
Sounds reasonable @tobybellwood so I've updated the PR to pin the versions to `3.0.0` based on the latest `main` update

**Comment by tobybellwood** [comment]
Nice! As I don't xdebug myself, I'll have to rely on you to test it out!

**Comment by dan2k3k4** [comment]
Is it possible to pull from the PR for the Docker images? Or I have to build it all locally?

**Comment by tobybellwood** [comment]
testlagoon/php-7.4-fpm:pr-41 and
testlagoon/php-7.4-cli-drupal:pr-41 should be on docker hub :-)

**Comment by twerthmueller** [comment]
Is there any progress to get Xdebug 3 as the default version in the PHP images you provide?

**Comment by AlexSkrypnyk** [comment]
@tobybellwood 
Could you please advise if there is anything can be done by the community here to roll Xdebug3 into PHP8 images. Thank you

**Comment by tobybellwood** [comment]
Yup, tell me they work!
```
 testlagoon/php-8.0-fpm:pr-41
 testlagoon/php-8.0-cli-drupal:pr-41
```
are the php8 test images with XDEBUG 3, just set `XDEBUG_ENABLE=true`

**Comment by fne-previon** [comment]
@tobybellwood Thanks for sharing the images. I've tested the images and found two issues

1. It only works if I don't set the `XDEBUG_ENABLE` variable. If I set `XDEBUG_ENABLE=true` (no matter if in the docker-compose.yml or in the dockerfile of the fpm container) Xdebug isn't shown within  phpinfo(). 
2. I had to set `XDEBUG_CONFIG="client_host=host.docker.internal"` in my dockerfile of the fpm container to get the step debugging to work..

**Comment by kasperg** [comment]
I am seeing the exact same behavior as above.

When setting `XDEBUG_ENABLE` in `docker-compose.yml` it is as if the XDebug extension is not loaded.

```
cli-drupal:/app$ echo $XDEBUG_ENABLE
true
```

```
cli-drupal:/app$ php -i | grep xdebug
/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini,
```

To me it seems as if the situation is caused by too much information being removed from the `docker-php-ext-xdebug.ini` file.

```
cli-drupal:/app$ cat /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini


xdebug.client_host=host.docker.internal
```

**Comment by kasperg** [comment]
Based on my findings I created a new PR #353. 

When using the test images XDebug 3 works for me with PHP 8 FPM. I am unsure about what made the difference.

Feel free to test them with the following images:

```
 testlagoon/php-8.0-fpm:pr-353
 testlagoon/php-8.0-cli-drupal:pr-353
 ```
