### ISSUE TITLE
Support for java projects

### ISSUE THREAD

**Issue by vincenzodnp** [uselagoon/lagoon-images#459]
I would like to add Lagoon support for java projects.
Lot of companies, still use stacks where the main application is java on Tomcat, Jetty or other Java Servlet. This could open the use of Lagoon to companies and agencies not involved in php/nodejs applications.

**Comment by tobybellwood** [comment]
Closing as no further recent conversation - please reopen if this use case or issue still exists.

sidenote, Java is such a wide ecosystem with no apparent universal conventions, it may be hard to present "one image to rule them all"
