### ISSUE TITLE
NewRelic integration not working for PHP versions >= 7.3

### ISSUE THREAD

**Issue by rafatwork** [uselagoon/lagoon-images#52]
The NewRelic integration doesn't seem to be working for PHP versions equal to or greater than 7.3

I can find this in the logs when the PHP container is started:

> php_1                | 2020-12-04 12:46:59.260 +0000 (36 36) warning: daemon connect(fd=4 uds=/tmp/.newrelic.sock) returned -1 errno=ENOENT. Failed to connect to the newrelic-daemon. Please make sure that there is a properly configured newrelic-daemon running. For additional assistance, please see: https://newrelic.com/docs/php/newrelic-daemon-startup-modes
> php_1                | Waiting for NewRelic Agent to be responsive. (1)
> php_1                | Waiting for NewRelic Agent to be responsive. (2)
> php_1                | Waiting for NewRelic Agent to be responsive. (3)
> php_1                | Waiting for NewRelic Agent to be responsive. (4)
> php_1                | Waiting for NewRelic Agent to be responsive. (5)
> php_1                | Waiting for NewRelic Agent to be responsive. (6)
> php_1                | Waiting for NewRelic Agent to be responsive. (7)
> php_1                | Waiting for NewRelic Agent to be responsive. (8)
> php_1                | Waiting for NewRelic Agent to be responsive. (9)
> php_1                | Waiting for NewRelic Agent to be responsive. (10)
> php_1                | [04-Dec-2020 12:47:09] NOTICE: fpm is running, pid 6
> php_1                | [04-Dec-2020 12:47:09] NOTICE: ready to handle connections

Easily reproducible with the amazeeio Drupal example (https://github.com/amazeeio/drupal-example).

This issue doesn't occur with PHP version 7.2 and below.

**Comment by rocketeerbkw** [comment]
Thanks for the report. We have reports that it works in our php 8 images, and php 7 is no longer supported.
