### ISSUE TITLE
drush/drush-launcher 0.8.0 and webflo/drupal-finder 1.2.0 can't find the drupal root

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon-images#54]
with the 21.12.0 we upgrade to `drush/drush-launcher` from version 0.6.0 to 0.8.0 (https://github.com/uselagoon/lagoon-images/pull/33/files#diff-dc5acee73eb46af5417e3bca288d2b9497183cd6c18a17c4ba274c7caf8ac5ea0L10)
which itself also upgraded to `webflo/drupal-finder` from 1.0.0 to 1.2.0 (https://github.com/drush-ops/drush-launcher/compare/0.6.0...0.8.0#diff-f37acfaa6b11f575a9a6f41a75fa73a61d0f8ebc2c9b8cddc215d8aca10e44f5L211 - check the composer.lock)

now it seems `webflo/drupal-finder` has an issue finding the drupal docroot if this is given:
```
.
├── composer.json
├── composer.lock
├── docroot
│   ├── LICENSE.txt
│   ├── README.php
│   ├── README.txt
│   ├── autoload.php
│   ├── core
│   ├── example.gitignore
│   ├── index.php
│   ├── modules
│   ├── profiles
│   ├── robots.txt
│   ├── sco
│   ├── sites
│   ├── themes
│   ├── update.php
│   └── web.config
├── drush
│   ├── README.md
│   ├── aliases.drushrc.php
│   ├── drushrc.php
│   └── policy.drush.inc
└── vendor
    └──[...]
```

with version 0.6.0:
```
cli-drupal:/app$ wget -O /usr/local/bin/drush "https://github.com/drush-ops/drush-launcher/releases/download/0.6.0/drush.phar" && chmod +x /usr/local/bin/drush
'/usr/local/bin/drush' saved
cli-drupal:/app$ drush --debug status
Drush Launcher Version: 0.6.0
ROOT: /app
DRUSH VERSION: 9
DRUPAL ROOT: /app/docroot
COMPOSER ROOT: /app
VENDOR ROOT: /app/vendor
```

with version 0.8.0:
```
cli-drupal:/app$ wget -O /usr/local/bin/drush "https://github.com/drush-ops/drush-launcher/releases/download/0.8.0/drush.phar" && chmod +x /usr/local/bin/drush
'/usr/local/bin/drush' saved
cli-drupal:/app$ drush --debug status
Drush Launcher Version: 0.8.0
ROOT: /app
DRUSH VERSION: 10
DRUPAL ROOT: /app
COMPOSER ROOT: /app
VENDOR ROOT: /app/vendor
```

and the worst, it also does not work inside the `/app/docroot` folder:
```
cli-drupal:/app$ cd docroot/
cli-drupal:/app/docroot$ drush --debug status
Drush Launcher Version: 0.8.0
ROOT: /app/docroot
DRUSH VERSION: 10
DRUPAL ROOT: /app
COMPOSER ROOT: /app
VENDOR ROOT: /app/vendor
```
(the `DRUPAL ROOT` should be `/app/docroot`)

the only workaround is to copy the `composer.json` into `/app/docroot`:
```
cli-drupal:/app/docroot$ cp ../composer.json .
cli-drupal:/app/docroot$ drush --debug status
Drush Launcher Version: 0.8.0
ROOT: /app/docroot
DRUSH VERSION:
DRUPAL ROOT: /app/docroot
COMPOSER ROOT: /app/docroot
VENDOR ROOT: /app/docroot/vendor
```
which is a horrible workaround

**Comment by Schnitzel** [comment]
found it after a lot of debugging, it's caused by this:
https://github.com/webflo/drupal-finder/commit/28d9da132ea6841fd9ee4c2e763c038225f982c0

but this only happens if the composer.json has this in it:

```
{
    "name": "drupal/drupal",
```

which according to naming conventions should not be used by a project composer.json

renaming the name in composer.json fixes everything:

```
cli-drupal:/app$ sed -i  's/drupal\/drupal/myproject\/drupal/' composer.json
cli-drupal:/app$ drush --debug status
Drush Launcher Version: 0.8.0
ROOT: /app
DRUSH VERSION: 10
DRUPAL ROOT: /app/docroot
COMPOSER ROOT: /app
VENDOR ROOT: /app/vendor
```

**Comment by tobybellwood** [comment]
thanks for the :detective: work @Schnitzel!
