### ISSUE TITLE
[PHP] Add igbinary extension to improve serialization performance

### ISSUE THREAD

**Issue by mxr576** [uselagoon/lagoon-images#564]
> [Igbinary](https://github.com/igbinary/igbinary) is a drop in replacement for the standard php serializer. Instead of the time and space consuming textual representation used by PHP's serialize, igbinary stores php data structures in a compact binary form. Memory savings are significant when using memcached, APCu, or similar memory based storages for serialized data. The typical reduction in storage requirements are around 50%. The exact percentage depends on your data.

See also related DrupalCon Prague 2022 session: https://events.drupal.org/prague2022/sessions/drupal-performances-real-production-projects

**Comment by tobybellwood** [comment]
Because this requires you to replace serialize and unserialize function calls with [igbinary_serialize and igbinary_unserialize](https://github.com/igbinary/igbinary/blob/master/igbinary.php) - this is better as an optional add-in
