### ISSUE TITLE
22.10.0 tags missing in dockerhub

### ISSUE THREAD

**Issue by Feng-Shui** [uselagoon/lagoon-images#573]
Morning,

I can't seem to find the 22.10.0 tags in dockerhub.

 => ERROR [internal] load metadata for docker.io/uselagoon/mariadb-10.6-drupal:22.10.0

https://hub.docker.com/r/uselagoon/mariadb/tags

Most recent tag I can see is 22.9.0

Am I missing something?

**Comment by tobybellwood** [comment]
ugh - thanks for the pickup - looks like a connectivity error (https://ci.lagoon.sh/blue/organizations/jenkins/lagoon-images/detail/22.10.0/1/) rerunning now :crossed_fingers:

**Comment by tobybellwood** [comment]
(now they're there)
