### ISSUE TITLE
Support Solr 9

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon-images#574]
https://solr.apache.org/docs/9_0_0/changes/Changes.html

Now released. No Drupal support yet, but I would imagine this is coming.

**Comment by tallytarik** [comment]
FYI, support for Solr 9 just dropped in [search_api_solr 4.3.0](https://www.drupal.org/project/search_api_solr/releases/4.3.0).

I was testing this out earlier and the Solr 9 build needs a few changes to get working. Sorry I don't have this in PR form yet, just getting these notes down:

- (in the Dockerfile) `-slim` Solr images no longer exist, so have to use something like `solr:9.3.0`
- the helper scripts dir has changed: in the Dockerfile and `solr-recreate.sh`, find+replace `/opt/docker-solr/scripts` => `/opt/solr/docker/scripts`
- there are [a few Solr XML config changes needed](https://git.drupalcode.org/project/search_api_solr/-/commit/8c20348efa94d84d412f252858dbe4d3d809d210) - this should be fine if you just update the default config based on what comes with the updated Drupal module

**Comment by tobybellwood** [comment]
ooh yeah - thanks @tallytarik - we'll get this back on track!

**Comment by rocketeerbkw** [comment]
Solr 9 images are available from [24.3.0](https://github.com/uselagoon/lagoon-images/releases/tag/24.3.0).
