### ISSUE TITLE
Add Mydumper and Myloader into the CLI image for faster MySQL dumps and restores

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon-images#612]
**Describe the feature**

At the moment it can take a long time to dump and restore databases if they are sufficiently large. For a recent site I was working on:

* Size: ~6.8 GB
* MySQLdump time: 2 minutes 11 seconds
* MySQL restore time: 38 minutes

It would be great if the `mydumper` and `myloader` CLI utilities where in the CLI pod.

**Mydumper and Myloader**

From https://github.com/maxbube/mydumper/releases

Example commands are:

```
time mydumper \
--host=<db-server-address> \
--user=<mydumper-username> \
--password=<mydumper-password> \
--outputdir=/db-dump/mydumper-files/ \
--rows=50000 \
-G -E -R \
--compress \
--build-empty-files \
--threads=16 \
--compress-protocol \
--regex '^(DbName\.)' \
-L /<mydumper-logs-dir>/mydumper-logs.txt
```

```
time myloader \
--host=<rds-instance-endpoint> \
--user=<db-username> \
--password=<db-password> \
--directory=<mydumper-output-dir> \
--queries-per-transaction=50000 \
--threads=16 \
--compress-protocol \
--verbose=3 -e 2><myload-output-logs-path>
```

Because the dumping and the loading are threaded, we can perform the processes much faster on database clusters with a lot of CPUs.

**Additional context**

Worth while to read https://medium.com/tensult/mydumper-myloader-and-my-experience-of-migrating-to-aws-rds-ff74fc9c1add

**Alternatives**

A go fork https://github.com/xelabs/go-mydumper has been written to which is API compatible.

**Comment by tobybellwood** [comment]
without global lock support this is worth pursuing

**Comment by seanhamlin** [comment]
Note from the AWS docs - https://docs.aws.amazon.com/prescriptive-guidance/latest/migration-large-mysql-mariadb-databases/mydumper.html

* Configure `mydumper` to divide each table into segments, such as 10,000 rows in each segment, and write each segment in a separate file. This makes it possible to import the data in parallel later.
* If you are using the InnoDB engine, use the `--trx-consistency-only` option to minimize locking.
* Using `mydumper` to export the database can become read-intensive, and the process can impact overall performance of the production database. If you have a replica database instance, run the export process from the replica. Before you run the export from the replica, stop the replication SQL thread. This helps the export process run more quickly.

**Comment by tobybellwood** [comment]
There's a handy explainer here about locking on RDS here - https://coderedpanda.wordpress.com/2020/04/11/mydumper-taking-consistent-backups/

Our DB users at the namespace level don't have SUPER privileges, nor can they pause replication on the replica. We could investigate the `trx-consistency-only` option if we can guarantee that all tables are InnoDB
