### ISSUE TITLE
Add environment variables to configure PHP session values

### ISSUE THREAD

**Issue by nicksantamaria** [uselagoon/lagoon-images#635]
The php.ini values below are valuable for securing session cookies. 

```
session.cookie_secure = 1
session.cookie_httponly = 1
session.cookie_samesite = Strict
```

Looks like they could get added to `images/php/fpm/00-lagoon-php.ini.tpl`. The default values should probably match [PHP's default values](https://www.php.net/manual/en/session.configuration.php#ini.session.cookie-secure).

**Comment by tobybellwood** [comment]
@seanhamlin - can we handle this in https://github.com/uselagoon/lagoon-images/pull/755

**Comment by seanhamlin** [comment]
I think these make sense as env vars, they seem like something people would want to change on a per site basis. Let me work this into the PR.
