### ISSUE TITLE
php-fpm php.ini still sets serialize_precision to 17 instead of the new -1 default

### ISSUE THREAD

**Issue by uandco** [uselagoon/lagoon-images#720]
Even when using php > 7.1, the image's php.ini still has `serialize_precision = 17`

This was the default till 7.1 and should now be changed to `-1`. See https://www.php.net/manual/en/ini.core.php

**Comment by seanhamlin** [comment]
Looks like there are a few sections missing too. Likely requires someone to reconcile the latest upstream ini changes with our customisations.

Link to the defaults:

* https://github.com/php/php-src/blob/php-8.0.28/php.ini-production
* https://github.com/php/php-src/blob/php-8.1.17/php.ini-production
* https://github.com/php/php-src/blob/php-8.2.4/php.ini-production

Bonus points for working out a way to automate this.
