### ISSUE TITLE
mysql runs upgrade even when `mysql_upgrade` is commented out in entrypoint

### ISSUE THREAD

**Issue by AlexSkrypnyk** [uselagoon/lagoon-images#740]
When updating `uselagoon/mariadb-drupal` image versions, there may be a new version of MariaDB provided.

When a new version is provided, the DB schemas needs to be updated by running `mysql_upgrade`.

The [entrypoint](https://github.com/uselagoon/lagoon-images/blob/main/images/mariadb/entrypoints/9999-mariadb-init.bash#L66) has such command and it runs when the MariaDB version is updated. All work as expected.

Now, if that line is removed from the entrypoint and an image is rebuild with an updated entrypoint file, when the container starts, the upgrade process still runs when `mysql` service starts. It runs, but such upgrade was not requested.

I'm trying to understand why this happens. Is this a standard `mysql` service behaviour to run such updates on it's own? If so - is there a way to disable this?

Or is this some configuration within `uselagoon/*` image that makes this process happen?

Steps to reproduce:
1. Checkout this repo
2. Switch to tag 23.2.1
3. Build a local `mariadb-drupal` image
4. Run container with volume mounted to host.
5. Import DB from dump (use any DB)
6. Stop image, the volume with DB should be preserved on host.
7. Switch to the latest tag of this repo. This would have an updated MariaDB version.
8. Edit entrypoint.bash file and comment-out `mysql_upgrade` line.
9. Build a new version of local `mariadb-drupal` image
10. Start the container
11. Observe upgrade running by examining docker logs for this container.

The impact of this is that on large databases the upgrades exceed the healthcheck times leading to broken builds. If possible, I would like to coordinate such schema updates rather than run them automatically (but even if we put a flag in the existing entrypoint to run `mysql_upgrade` only when requested, this would not help as the upgrade would still run... which is what this ticket is about).

**Comment by tobybellwood** [comment]
do you have a shareable log file we can look at to understand what happened - I would have thought that if the upgrade command wasn't there, none would happen?

**Comment by tobybellwood** [comment]
Just had a quick look, and I can't replicate this. I created the db in the volume, and can confirm that mysql_upgrade runs every time, because --force is set.

```
Version: '10.5.19-MariaDB'  socket: '/run/mysqld/mysqld.sock'  port: 0  MariaDB Server
2023-05-03  2:10:36 0 [Note] InnoDB: Buffer pool(s) load completed at 230503  2:10:36
1
1
Phase 1/7: Checking and upgrading mysql database
```

So I overrode the entrypoint and replaced the mysql_upgrade with an echo

```
    echo "mysql_upgrade is disabled"
    # mysql_upgrade --force
```

and as expected, on every run, the mysql_upgrade is not being called.

```
Version: '10.5.19-MariaDB'  socket: '/run/mysqld/mysqld.sock'  port: 0  MariaDB Server
2023-05-03  2:07:59 0 [Note] InnoDB: Buffer pool(s) load completed at 230503  2:07:59
1
1
mysql_upgrade is disabled
```

Even if I upgrade the database a full version, it doesn't get called
```
Version: '10.6.12-MariaDB'  socket: '/run/mysqld/mysqld.sock'  port: 0  MariaDB Server
2023-05-03  2:13:49 0 [Note] InnoDB: Buffer pool(s) load completed at 230503  2:13:49
1
1
mysql_upgrade is disabled
```

There must be some issue with how you're overriding that entrypoint?

**Comment by AlexSkrypnyk** [comment]
@tobybellwood 
thank you for looking into this. I will run tests on my side and report back.

**Comment by AlexSkrypnyk** [comment]
@tobybellwood 
Confirmed the source of my issue - I was "overriding" entrypoint on the wrong path which resulted in having 2 entrypoints: 1 original and 1 overridden.

Apologies for the noise.

Thank you for your help.
