### ISSUE TITLE
Update nginx for D10.1.x compatibility

### ISSUE THREAD

**Issue by AlexSkrypnyk** [uselagoon/lagoon-images#776]
https://www.drupal.org/node/2888767#nginx-php-fpm

**Comment by seanhamlin** [comment]
Reading the current Nginx configuration https://github.com/uselagoon/lagoon-images/blob/main/images/nginx-drupal/drupal.conf I don't know if we need to do any updates here?

Looking in the (current) Nginx configuration:

```
    ## Try to find a file with given URL, if not pass to Drupal
    try_files $uri @drupal;
```

As I understand https://www.drupal.org/node/2888767#nginx-php-fpm we just need to pass the request to Drupal for CSS and JS requests, where the file does not currently exist on disk.

I spun up a Drupal 10.1 site and see paths that look like this

```
http://drupal10-base.docker.amazee.io/sites/default/files/js/js_OMwyqXNRBhw12iYatF0mRiZ3_UyVdCWtaBpzVXR4jsc.js?scope=footer&delta=0&language=en-gb&theme=olivero&include=eJxdjVsOwyAMBC8E4Qw9ioFtREowtSFVbt9UeVTtl2fXK42u2jA7TwoTWOCi9Ep5oNDSAptTeRjOGwq7yi8IovWr9ZnD93EH4hUaeb1CoSWN1BIXqwhcIsm6e6Znx8mHswqPAtW9zExx0p9BhOdeAkxjzp7EHdd0hZyjDw9pc-n_bIAGqrjFOZU3gr1fvA
```

The paths work as you would expect.

**Comment by thomasdik1989** [comment]
Hi,

As mentioned in AIOSD-10575 the config file is not up to date compared with the web.config and the htaccess file.
We compared the config with https://git.drupalcode.org/project/drupal/-/blob/11.x/web.config?ref_type=heads and https://git.drupalcode.org/project/drupal/-/blob/9.5.x/web.config?ref_type=heads

As mentioned json and certain lockfiles are now publicly available.

Kind regards,

Thomas Dik

**Comment by seanhamlin** [comment]
Hey @thomasdik1989 , that issue sounds important, and adjacent to this issue. I think it warrants it's own issue (this one is purely about the changes needed to support CSS and JS aggregation in Drupal 10.1).

I will close this issue out, and raise a new one for your comment.
