### ISSUE TITLE
Can't build redis-6:23.6.0 on Lagoon

### ISSUE THREAD

**Issue by Feng-Shui** [uselagoon/lagoon-images#782]
In the process of upgrading to the 23.6.0 images, and I can't get the Redis image to build on Lagoon.

Dockerfile:

```
ARG LAGOON_VERSION=23.6.0
ARG LAGOON_REDIS_VERSION=6

FROM uselagoon/redis-${LAGOON_REDIS_VERSION}:${LAGOON_VERSION}

# This can be overridden in .env.
ENV MAXMEMORY=800mb
```

When building in Lagoon:

```
Building redis
Step 1/4 : ARG LAGOON_VERSION=23.6.0
Step 2/4 : ARG LAGOON_REDIS_VERSION=6
Step 3/4 : FROM uselagoon/redis-${LAGOON_REDIS_VERSION}:${LAGOON_VERSION}
23.6.0: Pulling from uselagoon/redis-6
mediaType in manifest should be 'application/vnd.docker.distribution.manifest.v2+json' not 'application/vnd.oci.image.manifest.v1+json'
Service 'redis' failed to build : Build failed
```

I can build the image locally without any issues.

**Comment by tobybellwood** [comment]
Thanks @Feng-Shui - I'll investigate!

**Comment by Feng-Shui** [comment]
I'm also seeing some other weird things, trying to run an install with the minimal profile gives me a PHP "No input file specified." error.  We do have some mild Nginx and PHP customisations, but I don't get the error on 23.5.

**Comment by Feng-Shui** [comment]
Ignore the above.

**Comment by tobybellwood** [comment]
Is the redis still an issue in Lagoon? I have tried to replicate in our infra so far unsuccessfully?

**Comment by Feng-Shui** [comment]
AFAIK, I'll trigger another build, if it fails I'll send you a build log link.

**Comment by Feng-Shui** [comment]
My apologies, it is building in Lagoon, it's not in govCSM GitLab.  Given that the GitLab config is in our repo, let me have a look at that first.  If it's still a problem I'll reopen an issue specific to GitLab in the govCMS support desk.  Sorry for the hassle!
