### ISSUE TITLE
curl is potentially broken in PHP 23.6.0

### ISSUE THREAD

**Issue by AlexSkrypnyk** [uselagoon/lagoon-images#793]
```bash
curl -sS -L "https://builds.matomo.org/matomo-1.15.0.tar.gz" --output=/tmp/matomo.tar.gz
````

stops mid-download

Tried multiple times with multiple versions.

Looks like `curl` does not pass the correct encoding header to the server and the server closes the connection.

This does work correctly in 23.4.0

**Comment by smlx** [comment]
I don't think `curl` accepts `--option=value` arguments. Instead it requires `--option value` arguments. Could you try running it with `--output /tmp/matomo.tar.gz`?

**Comment by AlexSkrypnyk** [comment]
That was an example. The problem is that download stops mid-way.

could you please run it from within the container

**Comment by smlx** [comment]
I can't reproduce it here with either `23.4.0` or `23.6.0`.

```
$ docker run --rm -it --entrypoint sh uselagoon/php-8.2-fpm:23.4.0 -c 'curl -sS -L "https://builds.matomo.org/matomo-1.15.0.tar.gz" --output /tmp/matomo.tar.gz; sha1sum /tmp/matomo.tar.gz'
d64bae91091eda6a7532ebec06aa70893b79e1f8  /tmp/matomo.tar.gz
```

```
$ docker run --rm -it --entrypoint sh uselagoon/php-8.2-fpm:23.6.0 -c 'curl -sS -L "https://builds.matomo.org/matomo-1.15.0.tar.gz" --output /tmp/matomo.tar.gz; sha1sum /tmp/matomo.tar.gz'
d64bae91091eda6a7532ebec06aa70893b79e1f8  /tmp/matomo.tar.gz
```

Do you have a command to reproduce the issue?

**Comment by smlx** [comment]
Did you manage to get `curl` working @AlexSkrypnyk?

**Comment by AlexSkrypnyk** [comment]
I was not able to reproduce this again. The builds were passing in CI, but failing in my local. Does not happen again.

Let's close this one for now. I will re-open it if I encounter this again. Thank you
