### ISSUE TITLE
Port Drupal blocks from #3308369 to Nginx configuration

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon-images#817]
See https://git.drupalcode.org/project/drupal/-/commit/2233484fbaabe30ecda8c15c49fed138b255be63 and https://www.drupal.org/project/drupal/issues/3308369 in which Drupal now blocks by default the following files.

```
yarn.lock
package.json
```

Originally raised in https://github.com/uselagoon/lagoon-images/issues/776#issuecomment-1700931371 by @thomasdik1989

**Comment by sjerdo** [comment]
This isn't the latest change to the filename regex, see: https://git.drupalcode.org/project/drupal/-/commit/6942a3897ffa04c6dc0eb62d32df22a4576fdaec

Also note the comment about the missing `package-lock.json` in comment https://www.drupal.org/project/drupal/issues/3308369#comment-14809579

We should include `package-lock.json` in the regex, so it could be changed to:
```
\.(engine|inc|install|make|module|profile|po|sh|.*sql|theme|twig|tpl(\.php)?|xtmpl|yml)(~|\.sw[op]|\.bak|\.orig|\.save)?$|^(\.(?!well-known).*|Entries.*|Repository|Root|Tag|Template|composer\.(json|lock)|web\.config|yarn\.lock|package(-lock)?\.json)$|^#.*#$|\.php(~|\.sw[op]|\.bak|\.orig|\.save)$
```
