### ISSUE TITLE
Canary builds

### ISSUE THREAD

**Issue by AlexSkrypnyk** [uselagoon/lagoon-images#829]
Is it possible to setup canary builds for all images when a new commit is pushed to `main` branch.

This will help a lot with testing of not-yet-released images by the community, which will also can help catch issues before the image is released.

**Comment by tobybellwood** [comment]
All images are built in a couple of docker-compose stacks on every push to every branch. If there's something else to test, feel free to suggest it?

**Comment by tobybellwood** [comment]
The two stacks are built and tested here - https://github.com/uselagoon/lagoon-images/tree/main/helpers

**Comment by tobybellwood** [comment]
And all built images are pushed into our testlagoon dockerhub organisation with a `main` or `pr-xxx` tag

eg:

`testlagoon/php-8.0-cli:pr-999` or `testlagoon/nginx:main`

**Comment by AlexSkrypnyk** [comment]
@tobybellwood 
thank you for explaining. This is sufficient.

I was not aware of `testlagoon`. https://docs.lagoon.sh/ have no mention of `testlagoon`.

**Comment by tobybellwood** [comment]
Yah - generally the images aren't for consumption - but where users collaborate on PR's we'll usually post the links for testing with.
