### ISSUE TITLE
Add environment variables to control New Relic logging

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon-images#845]
This is enabled automatically from version `v10.13.0` onwards.

Relevant configuration https://docs.newrelic.com/docs/logs/logs-context/configure-logs-context-php/#1-agent

```
newrelic.application_logging.enabled = true
newrelic.application_logging.metrics.enabled = true
newrelic.application_logging.forwarding.enabled = true
```

It would be nice to be able to opt out of the log and metric forwarding.

**Comment by tobybellwood** [comment]
should be pretty straightforward - does this make sense in [here](https://github.com/uselagoon/lagoon-images/blob/main/images/php-fpm/8.2.Dockerfile#L129) ?

add these vars, all defaulted to true, but overridable to false?
NEWRELIC_APPLICATION_LOGGING
NEWRELIC_APPLICATION_METRICS_LOGGING
NEWRELIC_APPLICATION_FORWARDING_LOGGING



```
        && sed -i -e "s/;newrelic.application_logging.enabled = .*/newrelic.application_logging.enabled = \"\${NEWRELIC_APPLICATION_LOGGING:-true}\"/" /usr/local/etc/php/conf.d/newrelic.ini \
        && sed -i -e "s/;newrelic.application_logging.metrics.enabled = .*/newrelic.application_logging.metrics.enabled = \"\${NEWRELIC_APPLICATION_METRICS_LOGGING:-true}\"/" /usr/local/etc/php/conf.d/newrelic.ini \
        && sed -i -e "s/;newrelic.application_logging.forwarding.enabled = .*/newrelic.application_logging.forwarding.enabled = \"\${NEWRELIC_APPLICATION_FORWARDING_LOGGING:-true}\"/" /usr/local/etc/php/conf.d/newrelic.ini \
 ```

**Comment by seanhamlin** [comment]
Yeah, that was all I was thinking, just tacking onto the existing framework for NR variables.
