### ISSUE TITLE
Enable New Relic and Blackfire for PHP 8.3 images

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon-images#905]
With the PR https://github.com/uselagoon/lagoon-images/pull/897 this adds PHP 8.3 support. Can we re-enable New Relic for the PHP 8.3 images?

**Comment by rocketeerbkw** [comment]
According to a blog post, blackfire also now supports php 8.3 https://blog.blackfire.io/blackfire-now-supports-php-8-3.html

Can't find any change logs for the agent, so just have to "trust" that renovatebot has picked the latest version and that version works with php 8.3 :roll_eyes:
