### ISSUE TITLE
Side effects after removing Drush launcher

### ISSUE THREAD

**Issue by AlexSkrypnyk** [uselagoon/lagoon-images#934]
https://github.com/uselagoon/lagoon-images/pull/877 has removed Drush Launcher and added 
```
ENV PATH="/app/vendor/bin:/home/.composer/vendor/bin:$PATH"
```

This made any bins located in `/app/vendor/bin` to take precedence over any other system commands with the same name. 

For example, when using `druidfi/gdpr-mysqldump`, it provides `mysqldump` command. After this change any calls to `mysqldump` will be using `/app/vendor/bin/mysqldump` instead of system's `mysqldump`.

The problem gets worse when a developer has no control over which system binary to use: in this specific case, Lagoon tasks are using `mysqldump` command (which actually uses `/app/vendor/bin/mysqldump`) with a flag `--no-tablespaces` that is not supported by `druidfi/gdpr-mysqldump`'s `mysqldump` leading to errors. And the developer cannot change that in Lagoon tasks.

I'm wondering if there is a better way to solve this by, potentially, only including `drush`'s location in the `PATH`.

**Comment by tobybellwood** [comment]
Would switching the order be an easy fix? That should just mean that any binary not in the existing PATH will be searched in the vendor dir - which should fix your issue?

`ENV PATH="$PATH:/app/vendor/bin:/home/.composer/vendor/bin"`

Tightly scoping it to the drush binary is also doable, but you might miss out on CLI access to the other composer-loaded binaries without adding a path override yourself?

**Comment by AlexSkrypnyk** [comment]
@tobybellwood 
Thank you for a rapid response

`ENV PATH="$PATH:/app/vendor/bin:/home/.composer/vendor/bin"` sounds like a good solution. 

Does it mean that I can put this into my Dockerfile (based on these images) to override or this change needs to take place in base images?

**Comment by tobybellwood** [comment]
I don't think it'll work in your images, as they will inherit the upstream path, and just append to that.

You can, however, probably override the entire PATH variable until we merge the fix in this month's release?

`ENV PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/app/vendor/bin:/home/.composer/vendor/bin"`
